# Generated by Django 5.0.4 on 2024-12-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackGroundTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(default=404)),
                ('message', models.TextField(blank=True, null=True)),
                ('data', models.TextField()),
                ('time', models.DateTimeField()),
                ('caller', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'BackGroundTaskDjango',
                'managed': True,
            },
        ),
    ]
