# Generated by Django 5.0.4 on 2024-12-12 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clockify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LemWorker',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('empId', models.CharField(db_column='name', max_length=50)),
            ],
            options={
                'db_table': 'LemWorker',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClientRep',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('clientId', models.ForeignKey(db_column='clientId', on_delete=django.db.models.deletion.CASCADE, to='Clockify.client')),
                ('empId', models.ForeignKey(db_column='empId', on_delete=django.db.models.deletion.DO_NOTHING, to='Clockify.employeeuser')),
                ('workspaceId', models.ForeignKey(db_column='workspaceId', on_delete=django.db.models.deletion.DO_NOTHING, to='Clockify.workspace')),
            ],
            options={
                'db_table': 'ClientRep',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('clientId', models.ForeignKey(db_column='clientId', on_delete=django.db.models.deletion.DO_NOTHING, to='Clockify.client')),
                ('workspaceId', models.ForeignKey(db_column='workspaceId', on_delete=django.db.models.deletion.DO_NOTHING, to='Clockify.workspace')),
            ],
            options={
                'db_table': 'Equipment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EqpRateSheet',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unitRate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('dayRate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('clientId', models.ForeignKey(db_column='clientId', on_delete=django.db.models.deletion.CASCADE, to='Clockify.client')),
                ('projectId', models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='Clockify.project')),
                ('workspaceId', models.ForeignKey(db_column='workspaceId', on_delete=django.db.models.deletion.DO_NOTHING, to='Clockify.workspace')),
                ('equipId', models.ForeignKey(db_column='equipId', on_delete=django.db.models.deletion.DO_NOTHING, to='LemApplication.equipment')),
            ],
            options={
                'db_table': 'EqpRateSheet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LemSheet',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lem_sheet_date', models.DateField()),
                ('lemNumber', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(blank=True, default=False)),
                ('clientRep', models.CharField(blank=True, default='----', max_length=50, null=True)),
                ('clientId', models.ForeignKey(db_column='clientId', on_delete=django.db.models.deletion.DO_NOTHING, to='Clockify.client')),
                ('projectId', models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='Clockify.project')),
                ('projectManagerId', models.ForeignKey(db_column='projectManagerId', on_delete=django.db.models.deletion.DO_NOTHING, to='Clockify.employeeuser')),
                ('workspaceId', models.ForeignKey(db_column='workspaceId', on_delete=django.db.models.deletion.DO_NOTHING, to='Clockify.workspace')),
            ],
            options={
                'db_table': 'LemSheet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EquipEntry',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('isUnitRate', models.BooleanField()),
                ('qty', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('equipId', models.ForeignKey(db_column='equipId', on_delete=django.db.models.deletion.DO_NOTHING, to='LemApplication.equipment')),
                ('lemId', models.ForeignKey(db_column='lemId', on_delete=django.db.models.deletion.CASCADE, to='LemApplication.lemsheet')),
            ],
            options={
                'db_table': 'EquipEntry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LemEntry',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('work', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('travel', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('calc', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('meals', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('hotel', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('lemId', models.ForeignKey(db_column='lemId', on_delete=django.db.models.deletion.CASCADE, to='LemApplication.lemsheet')),
                ('workerId', models.ForeignKey(db_column='workerId', on_delete=django.db.models.deletion.DO_NOTHING, to='LemApplication.lemworker')),
            ],
            options={
                'db_table': 'LemEntry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('clientId', models.ForeignKey(db_column='clientId', on_delete=django.db.models.deletion.DO_NOTHING, to='Clockify.client')),
                ('workspaceId', models.ForeignKey(db_column='workspaceId', on_delete=django.db.models.deletion.DO_NOTHING, to='Clockify.workspace')),
            ],
            options={
                'db_table': 'Role',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='lemworker',
            name='roleId',
            field=models.ForeignKey(db_column='roleId', on_delete=django.db.models.deletion.DO_NOTHING, to='LemApplication.role'),
        ),
        migrations.CreateModel(
            name='WorkerRateSheet',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('workRate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('travelRate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('calcRate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('mealRate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('hotelRate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('clientId', models.ForeignKey(db_column='clientId', on_delete=django.db.models.deletion.CASCADE, to='Clockify.client')),
                ('projectId', models.ForeignKey(db_column='projectId', on_delete=django.db.models.deletion.CASCADE, to='Clockify.project')),
                ('roleId', models.ForeignKey(db_column='roleId', on_delete=django.db.models.deletion.DO_NOTHING, to='LemApplication.role')),
                ('workspaceId', models.ForeignKey(db_column='workspaceId', on_delete=django.db.models.deletion.DO_NOTHING, to='Clockify.workspace')),
            ],
            options={
                'db_table': 'WorkerRateSheet',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='clientrep',
            constraint=models.UniqueConstraint(fields=('empId', 'clientId', 'workspaceId'), name='unique_client_rep'),
        ),
        migrations.AddConstraint(
            model_name='eqpratesheet',
            constraint=models.UniqueConstraint(fields=('clientId', 'equipId', 'workspaceId', 'projectId'), name='unique_client_equip'),
        ),
        migrations.AddConstraint(
            model_name='lemsheet',
            constraint=models.UniqueConstraint(fields=('id', 'workspaceId'), name='unique_client_lem'),
        ),
        migrations.AddConstraint(
            model_name='lementry',
            constraint=models.UniqueConstraint(fields=('workerId', 'lemId'), name='unique_worker_entry'),
        ),
        migrations.AddConstraint(
            model_name='lemworker',
            constraint=models.UniqueConstraint(fields=('empId', 'roleId'), name='unique_emp_role'),
        ),
        migrations.AddConstraint(
            model_name='workerratesheet',
            constraint=models.UniqueConstraint(fields=('clientId', 'roleId', 'workspaceId', 'projectId'), name='unique_client_role'),
        ),
    ]
