# Generated by Django 5.0.4 on 2024-12-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clockify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequests',
            name='createdAt',
            field=models.DateTimeField(db_column='createdAt', default='2024-12-12'),
            preserve_default=False,
        ),
    ]
